version: '3'
services:
  web:
    container_name: app
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./:/app
     - /app/node_modules
    restart: always
    depends_on:
      - mongo
    links:
     - mongo
    environment:
     - MONGO_URL=mongodb://root:root@mongo/myapp?authSource=admin
     - PORT=3000
  mongo:
    image: mongo:4
    command: [--auth]
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always